config/routes.rb
Rails.application.routes.draw do
  root to: 'main#home'
  # config/routes.rb
  post '/login', to: 'sessions#create'
  get '/password_reset', to: 'password_resets#new'

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>OFSP</title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <link rel="stylesheet" href="styles.css">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-HwwvtgBNo3bZJJLYd8oVXjrBZt8cqVSpeBNS5n7C8IVInixGAoxmnlMuBnhbgrkm" crossorigin="anonymous"></script>
    
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/main/home.html.erb
<style>
  header {
      background-image: url('/assets/Main banner.jpg');
      background-size: cover;
      background-position: center;
      padding: auto;
      text-align: center;
      margin-bottom: 25px;
  }

  footer {
    background-color: #0763B4;
    text-align: center;
    color: white;
    position: fixed;
    width: 100%;
    bottom: 0;
    height: 30px;
    line-height: 30px;
    font-size: 14px;
    padding: 5px; /* Adjust the padding as needed */
    margin-top: 25px;
}

footer a {
    color: white; /* Style the link color */
    text-decoration: none; /* Remove underline from the link */
}


  body {
      margin: auto;        
      min-height: 100vh; /* Ensure the body takes at least the full height of the viewport. */
      display: flex;
      flex-direction: column;
  } 
  .container {
            flex: 2; /* Make the container flex to occupy remaining vertical space. */
        }

</style>
<body>
    <div class="<div class="container">
      <header>
        <img src="/assets/Main banner.jpg" alt="banner" style="width: 100%; height: auto;">
      </header>
    </div>
    <div class="container-fluid">
      <div class="row justify-content-center">
        <div class="col-sm-4">
          <div>
            <h5 style='text-align:center; font-family: "Times New Roman";margin-top: 5px; font-size: 20px;'>Welcome</h5>
            <h6 style="text-align: center; font-family: 'monospace';">to</h6>
            <h6 style="text-align: center; font-size: 20px; font-family: 'noto' ; color:#0763B4">Orphan Care Family Support Program</h6>
            <p style="text-align:center; font-size: 15px;">"Orphans are the only ones who get to choose their fathers, and they love them twice as much."</p>
          </div>
          <%= form_with model: @user, url: login_path, method: :post do |form| %>
            <div class="mb-3">
              <%= form.text_field :email, class: "form-control", id: "exampleFormControlInput1", placeholder: "Email address" %>
            </div>
            <div class="mb-3">
              <%= form.password_field :password, class: "form-control", id: "exampleFormControlInput2", placeholder: "Password" %>
            </div>
            <div class="mb-3"> <!-- Add margin to this div to create space -->
              <%= link_to "Forget your password?", password_reset_path, class: "mt-3 text-center" %>
            </div>
            <div class="d-grid gap-2 col-6 mx-auto">
              <%= form.submit "Sign In", class: "btn btn-primary center" %>
            </div>
          <% end %>
        </div>
      </div>
    </div>
    <div class="<div class="container">
      <footer>
        <p><a href="/" target="_blank"> </a></p>
      </footer>
    </div> 
  </div>
</body>  